### ISSUE TITLE
Wanted: polling booth geolocation data

### ISSUE THREAD

**Issue by answerquest** [datameet/india-election-data#15]
There's plenty of new articles announcing ECI's putting 1lakh+ booths on google map. But the website, http://psleci.nic.in/Default.aspx gives the polling station markers only one at a time (and errors out if you wait too long), and the coding seems to be built to keep things closed-source. It is possible to scrape that data?

**Comment by raphael-susewind** [comment]
You can check out the complete dataset here:
http://dx.doi.org/10.4119/unibi/2674065. Its based on 2014 data from the
ECI - Raphael

**Comment by answerquest** [comment]
Thanks raphael, but that website doesn't seem so enthusiastic on sharing.. the download is v.low speed and dropping off. I'll try again a few hours later.
